/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import javax.swing.JOptionPane;
import DB.*;
import Model.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Big Nigga Dude
 */
public class LoginForm extends javax.swing.JFrame {
    private String status;
    DAO myDao = new DAO();
    Model myModel = new Model();

    public LoginForm() {
        initComponents();
    }

    public void clear() {
        usernameTF.setText("");
        passwordPF.setText("");
    }
    public String setStatus(){
        return this.status=usernameTF.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLbl = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        usernameLbl = new javax.swing.JLabel();
        usernameLbl1 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordLbl.setBackground(new java.awt.Color(102, 0, 102));

        loginBtn.setBackground(new java.awt.Color(102, 0, 102));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Login-Door-48.png"))); // NOI18N
        loginBtn.setName("LOGIN"); // NOI18N
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(102, 0, 102));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Exit-03-48.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        usernameLbl.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl.setText("USERNAME");

        usernameLbl1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        usernameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl1.setText("PASSWORD");

        usernameTF.setBackground(new java.awt.Color(255, 255, 255));
        usernameTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN KU");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Lock-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");

        passwordPF.setBackground(new java.awt.Color(255, 255, 255));
        passwordPF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        passwordPF.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout passwordLblLayout = new javax.swing.GroupLayout(passwordLbl);
        passwordLbl.setLayout(passwordLblLayout);
        passwordLblLayout.setHorizontalGroup(
            passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLblLayout.createSequentialGroup()
                .addGroup(passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(usernameLbl)
                        .addGap(59, 59, 59)
                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(usernameLbl1)
                        .addGap(57, 57, 57)
                        .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(loginBtn)
                        .addGap(134, 134, 134)
                        .addComponent(exitBtn))
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordLblLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        passwordLblLayout.setVerticalGroup(
            passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLblLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(usernameLbl))
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordLblLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(usernameLbl1))
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(passwordLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn)
                    .addComponent(exitBtn)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (usernameTF.getText().equals("") || String.valueOf(passwordPF.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(null, "Username Atau Password Tidak Boleh Kosong", "PERPUSTAKAAN KU : LOGIN", JOptionPane.WARNING_MESSAGE);
        } else {
            myModel.setUsername(usernameTF.getText());
            myModel.setPassword(String.valueOf(passwordPF.getPassword()));
            try {
                if (myDao.login(myModel)) {
                    MemberForm a = new MemberForm();
                    this.dispose();
                    a.status=usernameTF.getText();
                    a.run(usernameTF.getText());
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            clear();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Ingin Keluar ?", "Perpustakaan", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LoginForm myLogin = new LoginForm();
        myLogin.run();
    }

    public void run() {
        LoginForm myLogin = new LoginForm();
        myLogin.setLocationRelativeTo(null);
        myLogin.setResizable(false);
        myLogin.setSize(565, 450);
        myLogin.setTitle("PERPUSTAKAAN KU");
        myLogin.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel passwordLbl;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel usernameLbl1;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
