/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import DB.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Model.*;

/**
 *
 * @author Big Nigga Dude
 */
public class MemberForm extends javax.swing.JFrame {
    String status;
    DAO myDao = new DAO();
    Model myModel = new Model();
    public boolean edit = false;
    public boolean delete = false;

    public MemberForm() throws SQLException {
        initComponents();
       
        dataTable();
        saveBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        addNEditOff();
        idTF.setEnabled(false); 
        run("a");
            
 
    }
    public void statusChecker(String status){
        if(myDao.statusChecker(status)==false){   
             usernameTF.setVisible(false);
            passwordTF.setVisible(false);
            insertBtn.setVisible(false);
            editBtn.setVisible(false);
            deleteBtn.setVisible(false);
            resetBtn.setVisible(false);
            saveBtn.setVisible(false);
            cancelBtn.setVisible(false);
            usernameLbl.setVisible(false);
            passwordLbl.setVisible(false);
        }
        else{
            System.out.println("TRUE MIN");
        }
        
    }
    public void dataTable() throws SQLException {
        myTable.setModel(myDao.showData());
    }

    public void clearTF() {
        namaTF.setText("");
        jurusanTF.setText("");
        usernameTF.setText("");
        passwordTF.setText("");
    }

    public void addNEditOn() {
        saveBtn.setEnabled(true);
        cancelBtn.setEnabled(true);
        namaTF.setEnabled(true);
        jurusanTF.setEnabled(true);
        usernameTF.setEnabled(true);
        passwordTF.setEnabled(true);
        usernameTF.setEditable(true);
        insertBtn.setEnabled(false);
        editBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }

    public void addNEditOff() {
        saveBtn.setEnabled(false);
        cancelBtn.setEnabled(false);

        namaTF.setEnabled(false);
        jurusanTF.setEnabled(false);
        jurusanTF.setEnabled(false);
        usernameTF.setEnabled(false);
        passwordTF.setEnabled(false);
        insertBtn.setEnabled(true);
        editBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        clearTF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaTF1 = new javax.swing.JTextField();
        jurusanTF2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PERPUSTAKAAN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();
        idTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        jurusanTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        PERPUSTAKAAN1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();

        namaTF1.setBackground(new java.awt.Color(255, 255, 255));
        namaTF1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N

        jurusanTF2.setBackground(new java.awt.Color(255, 255, 255));
        jurusanTF2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N

        jButton2.setText("jButton2");

        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USERNAME");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERPUSTAKAAN KU");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveBtn.setBackground(new java.awt.Color(102, 0, 102));
        saveBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Save-48.png"))); // NOI18N
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 181, 68, -1));

        deleteBtn.setBackground(new java.awt.Color(102, 0, 102));
        deleteBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Garbage-Closed-48.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 181, 70, -1));

        insertBtn.setBackground(new java.awt.Color(102, 0, 102));
        insertBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        insertBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Add-New-48.png"))); // NOI18N
        insertBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertBtnMouseExited(evt);
            }
        });
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 121, 68, -1));

        editBtn.setBackground(new java.awt.Color(102, 0, 102));
        editBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Data-Edit-48.png"))); // NOI18N
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 121, 70, -1));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, -1, -1));

        PERPUSTAKAAN.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        PERPUSTAKAAN.setForeground(new java.awt.Color(255, 255, 255));
        PERPUSTAKAAN.setText("DATA ANGGOTA");
        jPanel1.add(PERPUSTAKAAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        myTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 357, 605, 140));

        idTF.setBackground(new java.awt.Color(255, 255, 255));
        idTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jPanel1.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 110, 240, -1));

        namaTF.setBackground(new java.awt.Color(255, 255, 255));
        namaTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jPanel1.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 140, 240, -1));

        jurusanTF.setBackground(new java.awt.Color(255, 255, 255));
        jurusanTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jPanel1.add(jurusanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 170, 240, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JURUSAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, -1, -1));

        usernameTF.setBackground(new java.awt.Color(255, 255, 255));
        usernameTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 202, 240, -1));

        passwordTF.setBackground(new java.awt.Color(255, 255, 255));
        passwordTF.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 234, 240, -1));

        resetBtn.setBackground(new java.awt.Color(102, 0, 102));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Command-Reset-48.png"))); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 243, 70, -1));

        cancelBtn.setBackground(new java.awt.Color(102, 0, 102));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Delete-48.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 243, 70, -1));

        usernameLbl.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl.setText("USERNAME");
        jPanel1.add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 206, -1, -1));

        passwordLbl.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("PASSWORD");
        jPanel1.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 238, -1, -1));

        PERPUSTAKAAN1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        PERPUSTAKAAN1.setForeground(new java.awt.Color(255, 255, 255));
        PERPUSTAKAAN1.setText("PERPUSTAKAAN KU :");
        jPanel1.add(PERPUSTAKAAN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        searchBtn.setBackground(new java.awt.Color(102, 0, 102));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Search-48.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        int response = JOptionPane.showOptionDialog(this,
                "Ingin Menambah Data?",
                "Perpustakaan Ku",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (response == JOptionPane.YES_OPTION) {
            addNEditOn();
            clearTF();
            try {
                idTF.setText(myDao.idChecker(myModel));
            } catch (SQLException ex) {
                Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int response = JOptionPane.showOptionDialog(this,
                "Simpan Data?",
                "Perpustakaan Ku",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (response == JOptionPane.YES_OPTION) {
            if (namaTF.getText().equals("") || jurusanTF.getText().equals("") || usernameTF.getText().equals("") || passwordTF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data Harus Lengkap");
                addNEditOn();
            } else {
                myModel.setNama(namaTF.getText());
                myModel.setJurusan(jurusanTF.getText());
                myModel.setUsername(usernameTF.getText());
                myModel.setPassword(passwordTF.getText());
                if (edit) {
                    myDao.editData(myModel);
                    edit = false;
                     addNEditOff();
                } else {
                    if (myDao.usernameChecker(myModel)) {                     
                         myDao.insertData(myModel);
                         addNEditOff();
                         clearTF();
                    }
                    else{
                       addNEditOn();
                    }                 
                }
                try {
                    dataTable();     
                } catch (SQLException ex) {
                    Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_saveBtnActionPerformed

    private void myTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTableMouseClicked
        int row = myTable.getSelectedRow();
        idTF.setText(myTable.getValueAt(row, 0).toString());
        namaTF.setText(myTable.getValueAt(row, 1).toString());
        jurusanTF.setText(myTable.getValueAt(row, 2).toString());

    }//GEN-LAST:event_myTableMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int response = JOptionPane.showOptionDialog(this,
                "Ingin Mengubah Data?",
                "Perpustakaan Ku",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        edit = true;
        if (response == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Ada Di Table (Klik)", "Perpustakaan KU : Edit", JOptionPane.INFORMATION_MESSAGE, null);
            addNEditOn();
            idTF.setEnabled(false);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int response = JOptionPane.showOptionDialog(this,
                "Hapus Data ?",
                "Perpustakaan Ku : Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (response == JOptionPane.YES_OPTION) {
            if (!idTF.getText().equals("")) {
                delete = true;
                if (delete) {
                    try {
                        dataTable();
                        myModel.setId(idTF.getText());
                        myDao.deleteData(myModel);
                        JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus", "Perpustakaan KU : Delete", JOptionPane.INFORMATION_MESSAGE, null);
                        delete = false;
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang Dipilih", "Perpustakaan KU : Delete", JOptionPane.INFORMATION_MESSAGE, null);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang Dipilih", "Perpustakaan KU : Delete", JOptionPane.WARNING_MESSAGE, null);
            }
            addNEditOff();
            clearTF();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void insertBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseEntered

    }//GEN-LAST:event_insertBtnMouseEntered

    private void insertBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseExited

    }//GEN-LAST:event_insertBtnMouseExited

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        clearTF();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        addNEditOff();
        clearTF();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String search = JOptionPane.showInputDialog(null, "Cari berdasarkan ID,Nama,Atau Jurusan", "PERPUSTAKAAN KU : CARI", JOptionPane.QUESTION_MESSAGE);
        try {
            myTable.setModel(myDao.searchData(search));
        } catch (SQLException ex) {
            Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

//    public static void main(String args[]) throws SQLException {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        MemberForm x = new MemberForm();
//        x.run();
//    }

    public void run(String m) throws SQLException {
        
        this.setLocationRelativeTo(null); System.out.println(myDao.statusChecker(m)); 
        this.setResizable(false);            
           if(myDao.statusChecker(status)==false){   
             usernameTF.setVisible(false);
            passwordTF.setVisible(false);
            insertBtn.setVisible(false);
            editBtn.setVisible(false);
            deleteBtn.setVisible(false);
            resetBtn.setVisible(false);
            saveBtn.setVisible(false);
            cancelBtn.setVisible(false);
            usernameLbl.setVisible(false);
            passwordLbl.setVisible(false);
        }
        else{
            System.out.println("TRUE MIN");
        }
        this.setVisible(true);
        statusChecker(m);
            System.out.println(myDao.statusChecker(m)); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PERPUSTAKAAN;
    private javax.swing.JLabel PERPUSTAKAAN1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton insertBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jurusanTF;
    private javax.swing.JTextField jurusanTF2;
    private javax.swing.JTable myTable;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField namaTF1;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
